spring:

  ## H2 DataBase
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 40

  ## JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  #    show-sql: true

## JWT
jwt:
  secret: "ohjuhyeonspringtemplate123test21e13dweefwfw"
  token:
    refresh-expires: 1200000 # 20분
    access-expires: 600000 # 10분

## Encrypt
encrypt:
  key: "templatetestohju" # 16byte

## Social Login
security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: {kakao-client-id}
          redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: profile_nickname, account_email #동의 항목
          client-name: Kakao
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id